services:
  - type: web
    name: portfolio-rafaela
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    # Headers configurados no servidor Express para compatibilidade total

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user