services:
  - type: web
    name: portfolio-rafaela
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
    # IMPORTANTE: NÃO configure REPLIT_DOMAINS ou PORT
    # O Render define PORT automaticamente e a aplicação detecta o ambiente

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user